spring.data.mongodb.uri=mongodb://localhost:27017/docquintero
spring.data.mongodb.database=docquintero
server.port=8080

app.jwt.secret=mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong
app.jwt.expiration=86400000