package com.docquintero.consultorio.historiaclinica.model;

public enum CondicionDental {
    SANO,
    CARIES,
    FRACTURA,
    AUSENTE,
    RESTAURACION,
    RESTAURACION_MAL_ESTADO,
    AMALGAMA,
    AMALGAMA_MAL_ESTADO,
    CORONA,
    CORONA_PROVISORIA,
    CORONA_PROVISORIA_MAL_ESTADO,
    PERNO_MUNON,
    PERNO_MUNON_MAL_ESTADO,
    IMPLANTE,
    IMPLANTE_MAL_ESTADO,
    ENDODONCIA,
    ENDODONCIA_MAL_ESTADO,
    SELLANTE,
    EXTRACCION_INDICADA,
    LESION
}
